ShopSnacktvc1/shopsnackDC/shopsnackDC/Controllers/NhaSanXuatController.cs
using shopsnackDC.Models.BUS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace shopsnackDC.Controllers
{
    public class NhaSanXuatController : Controller
    {
        // GET: NhaSanXuat
        public ActionResult Index(String id, int page = 1, int pagesize = 2)
        {
            var ds = NhaSanXuatBUS.ChiTiet(id).ToPagedList(page, pagesize); ;
            return View(ds);
        }
    }
}

ShopSnacktvc1/shopsnackDC/shopsnackDC/Controllers/ShopDCController.cs
using PagedList;
using shopsnackDC.Models.BUS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shopsnackDC.Controllers
{
    public class ShopDCController : Controller
    {
        // GET: ShopDC
        public ActionResult Index(int page = 1, int pagesize = 2)
        {
            var db = shopsnackDCBUS.DanhSach().ToPagedList(page, pagesize); ;
            return View(db);
        }

        // GET: ShopDC/Details/5
        public ActionResult Details(String id)
        {
            var db = shopsnackDCBUS.ChiTietSP(id);
            return View(db);
        }

        // GET: ShopDC/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ShopDC/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShopDC/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ShopDC/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShopDC/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShopDC/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ShopSnacktvc1/shopsnackDC/shopsnackDC/Views/Shared/_FooterSnackDC.cshtml
<footer class="page-footer">
    <div class="footer-row">
        <footer class="footer-box1">
            <a href="@Url.Action("Index","Home")"><img class="logo" src="~/Asset/images/logo.png" alt="" style="margin-left: 20px; margin-bottom: 20px;"></a>
            <div class="social">
                <ul class="social-share">
                    <li class="social-item">
                        <i class="fab fa-facebook-square"></i>
                    </li>
                    <li class="social-item">
                        <i class="fab fa-twitter"></i>
                    </li>
                    <li class="social-item">
                        <i class="fab fa-telegram"></i>
                    </li>
                    <li class="social-item">
                        <i class="fab fa-linkedin"></i>
                    </li>
                </ul>
            </div>
            <p>© 2020 by Ngọc Diệp - Văn Cường</p>
        </footer> <!-- .footer-box1 -->
        <footer class="footer-box2">
            <div class="row">
                <div class="col">
                    <ul class="cskh">
                        <p class="h5">HỖ TRỢ KHÁCH HÀNG</p>
                        <li class="footer-link"><a href="">Hotline CSKH: 19001009</a></li>

                        <li class="footer-link"><a href="">Hệ thống cửa hàng</a></li>
                        <li class="footer-link"><a href="">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="col">
                    <ul class="">
                        <p class="h5">GIỚI THIỆU SHOP</p>
                        <li class="footer-link"><a href="./html/gioithieuchung.html">Giới thiệu chung</a></li>
                        <li class="footer-link"><a href="./html/chinhsachthanhtoan.html">Chính sách thanh toán</a></li>
                        <li class="footer-link"><a href="./html/chinhsachgiaohang.html">Chính sách giao hàng</a></li>
                        <li class="footer-link"><a href="./html/chinhsachdoitra.html">Chính sách đổi trả</a></li>
                        <li class="footer-link"><a href="./html/chinhsachbaomat.html">Chính sách bảo mật</a></li>
                    </ul>
                </div>
                <div class="col">
                    <ul class="">
                        <p class="h5">LIÊN HỆ</p>
                        <li class="footer-link">VP Phía Bắc: Tầng 17 tòa nhà GSOT, 48 Phố Tố Hữu, Trung Văn, Nam Từ Liêm, Hà Nội.</li>
                        <li class="footer-link">VP Phía Nam: Tầng 3, 49/10 Trần Quang Diệu, Phường 13, Quận 3, Hồ Chí Minh.</li>
                        <li class="footer-link">Điện thoại: 1900.1009</li>
                    </ul>
                </div>
            </div>
        </footer><!-- .footer-box2 -->
        <footer class="footer-box3">
            <div class="row">
                <div class="col">
                    <ul class="">
                        <p class="h5">ĐĂNG KÍ BẢN TIN</p>
                        <div class="control">
                            <i class="fas fa-newspaper    "></i>
                            <input name="email" type="email" placeholder="Nhập Email của bạn">
                            <i class="fas fa-arrow-right    "></i>
                        </div>
                        <div class="footer-payment">
                            <img class="img-responsive" src="~/Asset/images/footer-payment.png" alt="Accept Payment">
                        </div>
                    </ul>
                </div>
            </div>
        </footer><!-- .footer-box3 -->
    </div>
</footer> <!--======= .page-footer ======= -->

ShopSnacktvc1/shopsnackDC/shopsnackDC/Views/Shared/_HeaderSnackDC.cshtml
<div class="haha" style="margin-top: -98px; width: 1200px; height: 89px;">
    <div style="background-color: #ffffff; height: 51px;">
        <div class="brand">
            <a href="@Url.Action("Index","Home")"><img class="logo" src="~/Asset/images/logo.png" alt=""></a>
            <ul class="header-item" style="margin-top: -30px">
                <li class="item-hotline">Hotline: 1900.8079</li>
                <i class="fa fa-user-circle" aria-hidden="true"></i>
                <li class="item-account">
                    <span class="acc-top">Đăng nhập tài khoản</span><br>
                    <span class="acc-bottom">Tài khoản của bạn</span>
                </li>
                <i class="fas fa-shopping-bag" aria-hidden="true"></i>
                <li class="item-cart">GIỎ HÀNG</li>
                
            </ul>
        </div> <!-- .brand -->
    </div>
    <div class="nav-bar">
        <ul class="nav-item" style="text-align: center">
            <li><a href="./index.html"><i class="fas fa-home    "></i>@Html.ActionLink("Trang chủ", "Index", "Home")</a></li>
            @Html.Partial("_NhaSanXuat", shopsnackDC.Models.BUS.NhaSanXuatBUS.DanhSach()) @*TRUY XUẤT TRỰC TIẾP sau đó phải cập nhật lại cho tk peta poco*@
            <li><a href=""><i class="fab fa-slack"></i>@Html.ActionLink("Snack", "Index", "ShopDC")</a></li>
            <li><a href="~/Views/ShopDC/Index.cshtml"><i class="fas fa-newspaper    "></i>Kẹo</a></li>
            <li><a href="./html/tintuc.html"><i class="fas fa-newspaper    "></i>GUM & MINTS</a></li>
            <li><a href="./html/tintuc.html"><i class="fas fa-newspaper    "></i>Tin tức</a></li>
            <li><a href="./html/taikhoan.html"><i class="fas fa-user-alt    "></i>Tài khoản</a></li>
            <li><a href=""><i class="fas fa-search    "></i></a></li>
        </ul>
    </div> <!-- .nav-bar -->
    <div class="top-height"></div>
</div>

ShopSnacktvc1/shopsnackDC/shopsnackDC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShopSnacktvc1/shopsnackDC/shopsnackDC/Views/Shared/_MainLayout.cshtml
@{
    ViewBag.Title = "_MainLayout";
}


<!doctype html>
<html lang="en">
<head>
    <title>DC SHOP</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Content/faw511all.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/infProduct1.css" />

</head>
<body>
    <div class="body-main">

        @*Đổ dữ liệu theo kiểu html.partial sau đó chuyển vê mvchtmlstring*@    
    @{ 
        var headertvc = Html.Partial("_HeaderSnackDC");
        headertvc = new MvcHtmlString(headertvc.ToString());
    }
    @headertvc
        

        <div style="margin-top: 98px;">
            @RenderBody()
        </div>   



    @*Đổ dữ liệu theo kiểu render partial*@
    @{Html.RenderPartial("_FooterSnackDC"); }

   
    </div> <!-- .body-main -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ShopSnacktvc1/shopsnackDC/shopsnackDC/Views/Shared/_NhaSanXuat.cshtml
@model IEnumerable<shopsnackDCConnection.NhaSanXuat>

<li>
    <div class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="./html/laptop.html"><i class="fas fa-laptop"></i> Thương hiệu</a>
        <div class="dropdown-menu" style="background-color: black">
            @foreach (var item in Model)
            {
                <a class="dropdown-item" href="@Url.Action("Index","NhaSanXuat",new { id = item.MaNhaSX})">@item.TenNhaSX</a>
            }

        </div>
    </div>
</li>  